/**
 * QA API
 * API description in QA.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Answer } from './answer';
import { QuestionType } from './questionType';


export interface QAAllOf { 
    question?: string;
    choices?: Array<Answer>;
    maxSelection?: number;
    selectionCounter?: number;
    point?: number;
    submitted?: boolean;
    validated?: boolean;
    qType?: QuestionType;
}

