/**
 * QA API
 * API description in QA.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BaseAllOf { 
    id?: string;
    creationDate?: number;
    lastModifiedDate?: number;
    owner?: string;
    ownerOrganization?: string;
}

