/**
 * QA API
 * API description in QA.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Answer } from './answer';
import { QAAllOf } from './qAAllOf';
import { Base } from './base';


export interface QA { 
    error?: string;
    exception?: string;
    id?: string;
    creationDate?: number;
    lastModifiedDate?: number;
    owner?: string;
    ownerOrganization?: string;
    question?: string;
    correctAnswers?: Array<number>;
    options?: Array<Answer>;
    submissions?: Array<number>;
    point?: number;
    submitted?: boolean;
    validated?: boolean;
}

