/**
 * QA API
 * API description in QA.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { QA } from '../model/qA';


import { Configuration }                                     from '../configuration';


export interface DefaultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * Lists the Question/Answers
    * 
    */
    getQaList(extraHttpRequestParams?: any): Observable<Array<QA>>;

}
